### ISSUE TITLE
README

### ISSUE THREAD

**Issue by gilcot** [seeschloss/sprint24-album#1]
Il serait bien d'ajouter au dépôt un `README.md` qui contienne : 

- le lien vers le site (https://seos.fr/blog/20211222.album.html) pour ne pas avoir à se répéter
- où trouver [le paquet sprint24-album](https://github.com/seeschloss/sprint24-album/blob/e8cda3097a64b4d5487c17147da356aa936589f3/album.tex#L14)
- un résumé en anglais de l'utilisation (organisation du répertoire de travail et appel du `Makfile` en listant les arguments/usages courants)

Merci pour cette belle contribution.

**Comment by seeschloss** [comment]
C'est ce repository qui est une annexe au billet de blog et non le contraire, il n'y a donc pas de raison à mon sens de faire un readme qui ne ferait que répéter ce que dit le billet.

`sprint24-album.sty` est bien commité dans le repo, donc pour le second point s'il n'est pas trouvé ça doit être une erreur de manipulation.

Je n'ai pas l'intention d'écrire des instructions en anglais mais je suis éventuellement ouvert aux pull requests.

**Comment by gilcot** [comment]
Je viens de voir pour le second point ; un souci chez moi en clonant le dépôt. 

Attention, je ne dis pas de « répéter ce que dit le billet » mais de faire « le lien vers le site [le billet en fait] » justement « pour ne pas avoir à se répéter » ! Mais n'eut été le troisième point, ce lien aurait pu se trouver juste dans la description du dépôt.   
En effet, quand on vient du billet, comme moi, pas de souci. Par contre quand on tombe sur ce dépôt d'une autre façon (recherche sur Github ou un moteur de recherche Internet ou autre) on tombe sur cet « annexe » hors contexte et je trouve ça dommage qu'on passe à côté d'une belle contribution pour si peu. 

Pour rester dans l'esprit du billet les instructions pourraient être en français remarque. J'ai pensé à l'anglais au cas où il y aurait une volonté d'atteindre un plus large public.  
Je peux contribuer cela dès que j'ai un moment dans la semaine.
