### ISSUE TITLE
xe?

### ISSUE THREAD

**Issue by gilcot** [seeschloss/sprint24-album#3]
Dans les dernières lignes du `Makefile` je lis : 

```make
album.pdf: album.tex photos.tex
	xelatex album.tex
```

Du coup, en allant regarder `album.tex`, je ne vois que le paquetage [_fontspec_](https://ctan.org/pkg/fontspec) qui nécessite à priori XeLaTeX ou LuaLaTeX. Mais il ne me semble pas avoir vu les principales commandes de ce paquetage. Il faudra donc, àmha, faire l'appel avec `latex` tout court après avoir viré la ligne chargeant ce paquetage.   
Si je me suis trompé, c'est le genre d'info qu'il faut mentionner dans le README #1 :)

**Comment by gilcot** [comment]
> Mais il ne me semble pas avoir vu les principales commandes de ce paquetage. 

Arf, j'avais pas les yeux en face des trous ; y a bien 

```latex
\setmainfont{Segoe UI}
```

Au temps pour moi. Par contre, cette police est disponible partout ? À en croire https://boowiki.info/art/polices-sans-serif/segoe-ui.html#Disponibilit.C3.A0 non… (en tout cas je confirme qu'elle n'est pas dans mon installation) En maintenant ces deux lignes, il faudra indiquer dans le README comment s'assurer de sa présence (et éventuellement des valeurs de remplacement)

**Comment by gilcot** [comment]
> En maintenant ces deux lignes, il faudra indiquer dans le README comment s'assurer de sa présence (et éventuellement des valeurs de remplacement)

Ce peut être un lien vers https://blog.seboss666.info/2015/04/ces-polices-libres-qui-remplacent-les-polices-microsoft-proprietaires/ si c'est toujours valable. 
Je trouve aussi https://fr.maisfontes.com/segoe-ui-symbol.police et https://fr.maisfontes.com/segoe-ui.police ; mais il faut un compte en suivant le lien vers le site de l'éditeur.

**Comment by seeschloss** [comment]
Je ne distribue pas la police parce que je n'en ai pas le droit, mais je ne changerai pas de police entre deux albums donc ça ne me sert à rien d'avoir une option pour ça. Mais j'accepterai une pull request qui ne modifie pas les valeurs par défaut.

**Comment by gilcot** [comment]
Oui, on est d'accord qu'il ne faut surtout pas la distribuer. Je pointais surtout l'absence d'informations (qui te seraient utiles aussi le jour où tu change/réinstalle de/ton ordi.)  
Je regarde ce que j'arrive à tirer de mon côté, et qui reste compatible, puis proposerai une PR :-)
